name: job_market
description: A new Flutter job circular app.


environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.13.6


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
